import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { SimpleInvoiceOrderByWithRelationInputObjectSchema as SimpleInvoiceOrderByWithRelationInputObjectSchema } from './objects/SimpleInvoiceOrderByWithRelationInput.schema';
import { SimpleInvoiceWhereInputObjectSchema as SimpleInvoiceWhereInputObjectSchema } from './objects/SimpleInvoiceWhereInput.schema';
import { SimpleInvoiceWhereUniqueInputObjectSchema as SimpleInvoiceWhereUniqueInputObjectSchema } from './objects/SimpleInvoiceWhereUniqueInput.schema';
import { SimpleInvoiceCountAggregateInputObjectSchema as SimpleInvoiceCountAggregateInputObjectSchema } from './objects/SimpleInvoiceCountAggregateInput.schema';
import { SimpleInvoiceMinAggregateInputObjectSchema as SimpleInvoiceMinAggregateInputObjectSchema } from './objects/SimpleInvoiceMinAggregateInput.schema';
import { SimpleInvoiceMaxAggregateInputObjectSchema as SimpleInvoiceMaxAggregateInputObjectSchema } from './objects/SimpleInvoiceMaxAggregateInput.schema';
import { SimpleInvoiceAvgAggregateInputObjectSchema as SimpleInvoiceAvgAggregateInputObjectSchema } from './objects/SimpleInvoiceAvgAggregateInput.schema';
import { SimpleInvoiceSumAggregateInputObjectSchema as SimpleInvoiceSumAggregateInputObjectSchema } from './objects/SimpleInvoiceSumAggregateInput.schema';

export const SimpleInvoiceAggregateSchema: z.ZodType<Prisma.SimpleInvoiceAggregateArgs> = z.object({ orderBy: z.union([SimpleInvoiceOrderByWithRelationInputObjectSchema, SimpleInvoiceOrderByWithRelationInputObjectSchema.array()]).optional(), where: SimpleInvoiceWhereInputObjectSchema.optional(), cursor: SimpleInvoiceWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), SimpleInvoiceCountAggregateInputObjectSchema ]).optional(), _min: SimpleInvoiceMinAggregateInputObjectSchema.optional(), _max: SimpleInvoiceMaxAggregateInputObjectSchema.optional(), _avg: SimpleInvoiceAvgAggregateInputObjectSchema.optional(), _sum: SimpleInvoiceSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.SimpleInvoiceAggregateArgs>;

export const SimpleInvoiceAggregateZodSchema = z.object({ orderBy: z.union([SimpleInvoiceOrderByWithRelationInputObjectSchema, SimpleInvoiceOrderByWithRelationInputObjectSchema.array()]).optional(), where: SimpleInvoiceWhereInputObjectSchema.optional(), cursor: SimpleInvoiceWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), SimpleInvoiceCountAggregateInputObjectSchema ]).optional(), _min: SimpleInvoiceMinAggregateInputObjectSchema.optional(), _max: SimpleInvoiceMaxAggregateInputObjectSchema.optional(), _avg: SimpleInvoiceAvgAggregateInputObjectSchema.optional(), _sum: SimpleInvoiceSumAggregateInputObjectSchema.optional() }).strict();