import type { Prisma } from '@prisma/client';
import * as z from 'zod';
import { ContactWhereInputObjectSchema as ContactWhereInputObjectSchema } from './objects/ContactWhereInput.schema';
import { ContactOrderByWithAggregationInputObjectSchema as ContactOrderByWithAggregationInputObjectSchema } from './objects/ContactOrderByWithAggregationInput.schema';
import { ContactScalarWhereWithAggregatesInputObjectSchema as ContactScalarWhereWithAggregatesInputObjectSchema } from './objects/ContactScalarWhereWithAggregatesInput.schema';
import { ContactScalarFieldEnumSchema } from './enums/ContactScalarFieldEnum.schema';
import { ContactCountAggregateInputObjectSchema as ContactCountAggregateInputObjectSchema } from './objects/ContactCountAggregateInput.schema';
import { ContactMinAggregateInputObjectSchema as ContactMinAggregateInputObjectSchema } from './objects/ContactMinAggregateInput.schema';
import { ContactMaxAggregateInputObjectSchema as ContactMaxAggregateInputObjectSchema } from './objects/ContactMaxAggregateInput.schema';
import { ContactAvgAggregateInputObjectSchema as ContactAvgAggregateInputObjectSchema } from './objects/ContactAvgAggregateInput.schema';
import { ContactSumAggregateInputObjectSchema as ContactSumAggregateInputObjectSchema } from './objects/ContactSumAggregateInput.schema';

export const ContactGroupBySchema: z.ZodType<Prisma.ContactGroupByArgs> = z.object({ where: ContactWhereInputObjectSchema.optional(), orderBy: z.union([ContactOrderByWithAggregationInputObjectSchema, ContactOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ContactScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ContactScalarFieldEnumSchema), _count: z.union([ z.literal(true), ContactCountAggregateInputObjectSchema ]).optional(), _min: ContactMinAggregateInputObjectSchema.optional(), _max: ContactMaxAggregateInputObjectSchema.optional(), _avg: ContactAvgAggregateInputObjectSchema.optional(), _sum: ContactSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ContactGroupByArgs>;

export const ContactGroupByZodSchema = z.object({ where: ContactWhereInputObjectSchema.optional(), orderBy: z.union([ContactOrderByWithAggregationInputObjectSchema, ContactOrderByWithAggregationInputObjectSchema.array()]).optional(), having: ContactScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(ContactScalarFieldEnumSchema), _count: z.union([ z.literal(true), ContactCountAggregateInputObjectSchema ]).optional(), _min: ContactMinAggregateInputObjectSchema.optional(), _max: ContactMaxAggregateInputObjectSchema.optional(), _avg: ContactAvgAggregateInputObjectSchema.optional(), _sum: ContactSumAggregateInputObjectSchema.optional() }).strict();